[package]
name = "pdf2comic"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
strip = true
codegen-units = 1

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
jpeg-encoder = "0.7"
lopdf = "0.36"
pdfium-render = "0.8"
png = "0.17"
rayon = "1"
zip = "2"
